[Options]
RemoveAll = 0
Backup = 1
Silent = 0
[Content]
;RemovePages = http://www.example.com/|http://www.example.com/page.asp
AddPages = http://www.fiat.it/|http://www.ferrari.it/|http://www.some.com/Page.asp
